version: '{build}'
configuration: Release
image: Visual Studio 2019 Preview

install:
- ps: |-
    choco install dotnetcore-sdk --version 3.0.100-preview7-012821 --pre

cache:
- C:\Users\appveyor\AppData\Local\Temp\1\chocolatey\vcredist140 -> .appveyor.yml
- C:\Users\appveyor\AppData\Local\Temp\1\chocolatey\dotnetcore-sdk -> .appveyor.yml

before_build:
- dotnet restore

build_script:
- dotnet build --configuration Release
  
after_test:
- dotnet pack [Main] --configuration Release --output ..

artifacts:
- path: '*.nupkg'

deploy:
  - provider: NuGet
    on:
      branch: /^(master|\d\.\d)$/
    api_key:
      secure: Tz4nbtNMTV00UjCtvQB7yiSC/F8BiSE5Iob9qb8QvO57jrwzFoBXIlcVV+fyTVwE
    artifact: /.*\.nupkg/